### PR TITLE
Added tests for AddEmbeddableConfigStepTest class and changed AddEmbeddableBadgeConfigStep class

### PR DESCRIPTION
**Pull request by yashpal2104**
Added tests for AddEmbeddableConfigStepTest class and changed the 'badgeConfig' field in the AddEmbeddableBadgeConfigStep from private to public to be used in the AddEmbeddableConfigStepTest class

### Testing done

Test automation passes.

### Submitter checklist
- [X] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your main branch!
- [X] Ensure that the pull request title represents the desired changelog entry
- [X] Please describe what you did

### CODE REVIEW

**Comment by yashpal2104** [comment]
@MarkEWaite just wanted to know if it is ok to change and refactor the previous tests and new tests by using a void setup() method to initialise the variables.
Also wanted to know if it is ok to change the 'badgeConfig' field in the AddEmbeddableBadgeConfigStep from private to public to be used in the AddEmbeddableConfigStepTest class.

**Comment by MarkEWaite** [comment]
> @MarkEWaite just wanted to know if it is ok to change and refactor the previous tests and new tests by using a void setup() method to initialise the objects used. 

Yes, absolutely.  That's a very good chocie.

> Also wanted to know if it is ok to change the 'badgeConfig' field in the AddEmbeddableBadgeConfigStep from private to public to be used in the AddEmbeddableConfigStepTest class. 

The change from private to package protected is reasonable to me, so long as a comment is included that it is intentionally package protected for testing purposes.  I pushed a comment noting that.

> Are these wildcard imports acceptable to use?

I don't object to the wildcard imports when used in tests.  I don't like wildcard imports in production code, but don't mind them in tests.

I'd prefer to not use mock objects, but I didn't see any way to do that with this class.  Thus, mock objects seem like the right choice here.

**Comment by MarkEWaite** [comment]
Don't forget to sync your copy of the master branch with the upstream copy of the master branch.

**Review by MarkEWaite — APPROVED** [review]
Thanks!

**Pull request merged**
