### PR TITLE
Add a test for RunBadgeAction

### PR DESCRIPTION
**Pull request by Subhojit-Dey1234**
## [JENKINS-70464] Added test case for `RunBadgeAction`

Added Test cases
Jira issue - [JENKINS-70464](https://issues.jenkins.io/browse/JENKINS-70464)

### Testing done

- [x] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your main branch!
- [x] Ensure that the pull request title represents the desired changelog entry
- [x] Please describe what you did
- [x] Link to relevant issues in GitHub or Jira
- [x] Link to relevant pull requests, esp. upstream and downstream changes
- [x] Ensure you have provided tests - that demonstrates feature works or fixes the issue

### CODE REVIEW

**Comment by MarkEWaite** [comment]
Thanks @Subhojit-Dey1234 .  You'll need to run `mvn spotless:apply` to format the source files according to the standard required by the `mvn verify` step.

**Comment by Subhojit-Dey1234** [comment]
@MarkEWaite thanks for mentioning. I have updated.

**Comment by abhishekmaity** [comment]
tagging #114 for getting it added in the list

**Review by abhishekmaity — APPROVED** [review]
Looks okay

**Review by MarkEWaite — APPROVED** [review]
I generally prefer to avoid mock objects when I can test the object with a `JenkinsRule` based test.  The `JenkinsRule` based test is closer to the way the object is used in a real Jenkins controller.

The mock tests that remain are tests that I could not see how to easily duplicate with a `JenkinsRule` test.  The `getUrl` test should be feasible by using a JenkinsRule that invokes a WebClient.  However, I ran out of time to do that additional effort.

Very nice pull request.  Ready to merge once the CI job passes.

**Pull request merged**
