### PR TITLE
add test for PublicBuildStatusAction.java

### PR DESCRIPTION
**Pull request by Vandit1604**
Add tests for `DoIcon()` , `DoIconForJob()` , `getUrlName()` , `getIconFileName()` , `getDisplayName()`  methods from [PublicBuildStatusAction,java](https://github.com/jenkinsci/embeddable-build-status-plugin/blob/master/src/main/java/org/jenkinsci/plugins/badge/actions/PublicBuildStatusAction.java)

See [JENKINS-70464](https://issues.jenkins.io/browse/JENKINS-70464) for more information
- [x] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your main branch!
- [x] Ensure that the pull request title represents the desired changelog entry
- [x] Please describe what you did
- [x] Link to relevant issues in GitHub or Jira
- [ ] Link to relevant pull requests, esp. upstream and downstream changes
- [ ] Ensure you have provided tests - that demonstrates feature works or fixes the issue

### CODE REVIEW

**Comment by MarkEWaite** [comment]
@Vandit1604 thanks very, very much for the added tests.  I'm not a big fan of mock objects, so I used this as an excuse to learn more about alternatives to structure tests in Jenkins.  Could you review the comments that I've inserted into the test methods and attempt a second time to add tests for the `doText` method?

I believe it can follow the same pattern as the `icon` method, though I have not implemented the test, so I may be wrong.

If you'd rather create a separate pull request for the `doText` method, I'm fine with that as well.  This pull request is a very nice addition to the plugin test suite, even without a test of the `doText` method.

**Comment by Vandit1604** [comment]
I'll add the test for DoText method in another PR as it was taking too much time to figure it out

**Comment by MarkEWaite** [comment]
Got it.  Thanks.  Nice use of the :rocket: emoji to indicate "ship it as it is".

**Comment by Vandit1604** [comment]
Thanks. It's my favourite emoji

**Pull request merged**
