### PR TITLE
Resolve incorrect badge examples when opened directly from URL

### LINKED ISSUE #278: Badge examples incorrect for some jobs if opened directly from URL
### Jenkins and plugins versions report

<details>
  <summary>Pipeline job that alternates success, failure, and unstable</summary>

  
  ```text
def win32BuildBadge = addEmbeddableBadgeConfiguration(id: "win32build", subject: "Windows Build")

def RunBuild() {
    echo 'Sleeping instead of running the build'
    sleep 10
    int buildNumber = env.BUILD_ID as int
    if ((buildNumber % 3) == 0) {
        error("Failing for fun")
    }
    if ((buildNumber % 3) == 1) {
        unstable("Unnstable for entertainment")
    }
}

pipeline {
    agent any
    stages {
        stage('Building') {
            steps {
                script {
                    win32BuildBadge.setStatus('running')
                    try {
                        RunBuild()
                        win32BuildBadge.setStatus('passing')
                    } catch (Exception err) {
                        win32BuildBadge.setStatus('failing')

                        /* Note: If you do not set the color
                                 the configuration uses the best status-matching color.
                                 passing -> brightgreen
                                 failing -> red
                                 ...
                        */
                        win32BuildBadge.setColor('pink')
                        error 'Build failed'
                    }
                }
            }
        }
    }
}
  ```

</details>

### What Operating System are you using (both controller, and any agents involved in the problem)?

Linux controller as described in [my docker-lfs repository](https://github.com/MarkEWaite/docker-lfs/tree/lts-with-plugins)

### Reproduction steps

1. Run the job at least 3 times so that there are jobs results that include success, failure, and unstable
2. Open a specific build of the job (for example, build 1) and click the "Embeddable build status" link on the page.  Note that the examples are displayed correctly.
3. Modify the URL in the web browser to use a different build number (for example, build 2) and press enter to load that page.  Note that the example is not displayed correctly.  It includes a broken image and `null-refererbadge/icon?subject=Custom%20Subject&status=Any%20State&color=darkturquoise`

### Expected Results

Example should be correct on the page

### Actual Results

a broken image and `null-refererbadge/icon?subject=Custom%20Subject&status=Any%20State&color=darkturquoise`

screencapture-mark-pc2-markwaite-net-8080-job-embeddable-status-example-pipeline-7-badge-2023-12-24-23_10_28-edit

### Anything else?

_No response_

### Are you interested in contributing a fix?

_No response_

### PR DESCRIPTION
**Pull request by sridamul**
Closes #278 

### Approach:
Replaced the `getReferer()` method with `getRequestURL()` (I am not sure if it is the optimal way to do it, but it fixes the issue without any flaws). Also modified the test cases to use getRequestURL() with and without `badge/` at the end of the URL.

### Testing done

Before:
before

Now:

https://github.com/jenkinsci/embeddable-build-status-plugin/assets/107404972/76d047cb-1779-44c1-980a-95980c1c8175

```[tasklist]
### Submitter checklist
- [x] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your main branch!
- [x] Ensure that the pull request title represents the desired changelog entry
- [x] Please describe what you did
- [x] Link to relevant issues in GitHub or Jira
- [ ] Link to relevant pull requests, esp. upstream and downstream changes
- [x] Ensure you have provided tests - that demonstrates feature works or fixes the issue
```

### CODE REVIEW

**Comment by sridamul** [comment]
@MarkEWaite If possible Can you review this?

**Comment by MarkEWaite** [comment]
> @MarkEWaite If possible Can you review this?

Thanks for the ping @sridamul .  I have several other things that need my attention before I leave next week for several weeks of vacation.  I'm not sure that I'll have time to review this before mid March.

**Comment by sridamul** [comment]
Hey @MarkEWaite, Can you review this now?

**Comment by MarkEWaite** [comment]
Not yet @sridamul .  Other things are needing my attention this week.  I may be able to review it next week

**Comment by sridamul** [comment]
Hey @MarkEWaite Just a reminder ping to review this PR.

**Comment by MarkEWaite** [comment]
Thanks very much for the fix.  I introduced the bug when I added a copy button for the link examples and transitioned from defining the pages with groovy to defining them with jelly.  Jelly is more widely used for page definition in Jenkins than groovy and has better support for the most recent user interface updates.  The pull request that created the issue was:

* #222

**Review by MarkEWaite — APPROVED** [review]
Thanks very much for the fix!

**Pull request merged**
