### PR TITLE
New endpoint 'text' to return icon description

### PR DESCRIPTION
**Pull request by Brantone**
Instead of doing the image, nice to have it just return text.
Thus the icon's description was chosen.

### CODE REVIEW

**Comment by Brantone** [comment]
Main reason for adding this functionality here (as opposed to other methods to test if build is Success) is because of the "unprotected" feature it provides with respect to public access and circumventing security with "ViewStatus" permission.

**Comment by mgedmin** [comment]
Thank you for the pull request!

It would be nice to have some documentation mentioning that this is possible.  E.g. I've no idea what URL to request to get the new text-only status.

Also, a test wouldn't be amiss.

**Comment by Brantone** [comment]
Yup, most definitely can do. Wanted to vet if this was even a desirable feature first. I'll quickly write up the docs.
As for tests, I took a look at the existing ones and they don't even test if the badge coming back is the correct one ... so by adding tests to only validate text would still miss out on the icon, is that still ok?

**Comment by mgedmin** [comment]
IMHO even the simplest smoke test that just executes the code and discovers that nothing breaks is better than nothing.

**Comment by Brantone** [comment]
Rightyo, will do. Update inbound in the next day.

**Comment by rtyler** [comment]
Bump!

**Comment by Brantone** [comment]
Ugh. Apologies, thought this got committed. I see other updates now cause conflicts so will fix it all up.

**Comment by mgedmin** [comment]
TBH this part:

> It would be nice to have some documentation mentioning that this is possible. E.g. I've no idea what URL to request to get the new text-only status.

is probably more important than the test: what's the point of a feature if nobody knows it exists?

**Comment by Brantone** [comment]
So here's a question : since the README is pretty much blank, what's best location/method to get some documentation in there?

**Comment by Brantone** [comment]
Updated with tests and some more docs.
(only took 6 months, yeesh).

**Comment by Brantone** [comment]
Bump??

**Comment by Brantone** [comment]
Another shameless bump.

**Comment by Brantone** [comment]
Monthly bump :)

**Comment by mgedmin** [comment]
(I've given up my maintainer's hat after an Ubuntu upgrade broke my Java badly enough I can't even run Maven any more.  I hope the current maintainer can take a look!)

**Comment by Brantone** [comment]
Thx for info!! Only reason I'm pushing is I know of others waiting on it (ex: directing to PR and doing their own), so getting it out there would be nice :)
Cheers.

**Comment by yeka** [comment]
I also want this feature.
What's wrong with this PR?

**Comment by Brantone** [comment]
Huzzah!!! 😄

**Comment by rtyler** [comment]
This has not yet been released

**Comment by Brantone** [comment]
Right, I know there's still a release needed, but merge is first step ;)
Soooo ... about that 2nd step for doing a release? :)

**Comment by KostyaSha** [comment]
@rtyler do you maintain the plugin? Just pressing merge button wouldn't help users to get it released.

**Comment by oleg-nenashev** [comment]
Well @mgedmin is a maintainer from what I see.
But seems somebody from the cor eteam can go forward and release it. @jglick and @ndeloof have permissions according to https://github.com/jenkins-infra/repository-permissions-updater/blob/master/permissions/plugin-embeddable-build-status.yml. @KostyaSha , would you consider it as hijacking? ;)

**Comment by ndeloof** [comment]
I'm not a maintainer on this one.
https://github.com/jenkins-infra/repository-permissions-updater/pull/125

**Comment by mgedmin** [comment]
I'm pretty sure I relinquished maintainership to somebody else, but I don't remember who. :)

It was in the comments of some other pull request where I discovered (while unsuccessfully trying to make a release) that Ubuntu broke some Java subpackage that made Maven croak and die on my machine.

**Comment by KostyaSha** [comment]
@oleg-nenashev i would say that it case "2": CB people got permissions to handle only their own (customers?) issues. Now there is person from community and his change isn't released. PR exists since `Oct 22, 2015` and that bad for project from community perspective imho. 

> according to https://github.com/jenkins-infra/repository-permissions-updater/blob/master/permissions/plugin-embeddable-build-status.yml.

i can't even list this wonderful repo in UI.

@jglick @ndeloof could you noth review this change and finalise with release?

**Pull request merged**
