### PR TITLE
[JENKINS-21951] Support running status with correct background

### PR DESCRIPTION
**Pull request by cjuniet**
Add three different icons for running builds while preserving the previous
status background color. This should better follow "animated" BallColors.

### CODE REVIEW

**Comment by philandstuff** [comment]
:+1: to this change.  I would vote on the jira ticket, but it requires creating an account and doesn't accept openid login so that's too much friction.

**Comment by mgedmin** [comment]
Ooh, yes, this could be useful.

The images would need to be changed to match the new (shields.io) style.

Also, I worry about accessibility: if the background color is the only thing that distinguishes a running build that failed from a running build that succeeded last time, will color blind people be able to distinguish the two states?

**Comment by oleg-nenashev** [comment]
Still 👍 . A merge conflict needs to be resolved

**Comment by KostyaSha** [comment]
Probably images were replaced by svgs in master

**Comment by thomas-dee** [comment]
Thank you for your PR. This has been resolved with #31.

**Pull request closed without merging**
