### PR TITLE
Add build description to Parameter Resolver

### PR DESCRIPTION
**Pull request by LorensV8**

### CODE REVIEW

**Comment by LorensV8** [comment]
Hi, @thomas-dee @oleg-nenashev, could I kindly ask you, to review and process this PR, if possible? 🙂

**Comment by oleg-nenashev** [comment]
I put it in my review queue. Not sure I am a maintainer of this plugin though

**Comment by LorensV8** [comment]
@oleg-nenashev Thanks a lot. Just saw you as reviewer for previous PRs, so mentioned. Sorry for disturbing.

**Comment by LorensV8** [comment]
Hi, @thomas-dee. Thanks for reviewing this PR. Could you tell me, please, how it's possible to get these changes to release at https://plugins.jenkins.io/embeddable-build-status/ ?

**Pull request merged**
