### PR TITLE
Re-Indent SVG images files

### PR DESCRIPTION
**Pull request by alecharp**
With the next flat design image, having both images at the same height
might be a good thing.

### CODE REVIEW

**Comment by alecharp** [comment]
@reviewbybees

**Comment by mgedmin** [comment]
Could you elaborate?  Did shields.io change the badge height recently?

**Comment by alecharp** [comment]
I don't know if it's recent but even the "flat" design images are 20px height as https://github.com/jenkinsci/embeddable-build-status-plugin/blob/master/src/main/webapp/status/build-failing-red-flat.svg?short_path=9f2e346.

**Comment by ndeloof** [comment]
IIUC the change is just about the height attribute, right ?

[File change](https://github.com/jenkinsci/embeddable-build-status-plugin/pull/14/files) doesn't make it obvious. I wonder those svg files could be refactored as indented xml for a better contribution workflow

**Comment by ndeloof** [comment]
:+1: anyway

**Comment by alecharp** [comment]
@ndeloof yes the change is only about the height. I agree that having the SVG description in one-line makes the diff complicated. My latest commit fix the yellow image that had a rounded issue in the middle-bottom of the image.

**Comment by mgedmin** [comment]
Yeah, github's diffs of the SVGs are completely opaque. :(

When I originally added the SVGs I listed the curl/wget commands used to produce the images from the shields.io online generator, with screenshots for any human reviewers (of which there were none, which is how I ended up requesting and getting commit rights :).

I'm +1 for updating the SVGs to match the current shields.io style, it just wasn't clear to me what this PR was actually doing.

**Comment by mgedmin** [comment]
> Yeah, github's diffs of the SVGs are completely opaque. :(

(I meant on mobile; the desktop site has the fancy image comparator that you have to enable explictly for each SVG, with only one of them being active at a time, with an annoying loading delay.)

**Comment by alecharp** [comment]
Would you like that I commit a indented version of the SVG? So the  diffs might be easier next time?

**Comment by ndeloof** [comment]
would make sense IMHO

**Comment by alecharp** [comment]
Maybe I could do that in another PR? To keep this PR about the height of the images, no?

**Comment by ndeloof** [comment]
LGTM :+1:

**Comment by mgedmin** [comment]
Things that would make me hit the Merge button right now:
- two screenshots, one showing the current situation (a Jenkins badge next to a badge from some other service), and the other showing the changes after this PR is applied
- likewise an explanation for the yellow radius issue that I don't understand (why did it only affect the yellow button?  they were all generated the same way!)

Without the above I'd have to allocate 30 minutes for experimentation, and since I'm busy catching up with my mail after a 2-week vacation, I'm hard-pressed to find 30 minutes.  Sorry!

As for the other things, I think pretty-printing the SVG is a Good Idea.  (It'd be even better to rebase the PR and move the pretty-printing before the actual semantic changes, but I'll not insist.)

**Comment by alecharp** [comment]
The current situation compare to Coverall: 

capture d ecran 2015-03-23 a 13 50 34

The issue with the yellow logo was due to a missing find/replace. The result was the rounded border on the middle of the image:

capture d ecran 2015-03-23 a 13 49 40

**Comment by mgedmin** [comment]
I think you're comparing the plastic style with the flat style.

Check out http://projects.gedmin.as/#maintenance, where the badges produced by Travis, Jenkins and Coveralls all match (and all use the flat style).

I'm running embeddable-build-status-plugin 1.7-SNAPSHOT (i.e. a locally-built copy of master), since I'm new to this Jenkins plugin maintenance thing and can't figure out how to make releases :/

**Comment by alecharp** [comment]
my fix is done on the plastic images because the flat ones are already in 20px height. I'm comparing the plastic images with the coverall image, which is flat but that is not what I am comparing.

**Comment by mgedmin** [comment]
Plastic images should match the plastic style.  Check out the ?style=plastic example near the bottom of  http://shields.io/: it's 18px high.

If you want your badges to match Coveralls, use the flat style (which is the default in embeddable-build-status-plugin master).

I suspect what you actually want is a release of embeddable-build-status-plugin 1.7, so that you could use the flat style badges that match everything else out there without having to build it from the sources (or downloading built 1.7 snapshots from the CI server).

**Comment by alecharp** [comment]
Ok I didn't know about those plastics images for coverall. Thanks.

Do you know when you will release the 1.7 version?

**Comment by mgedmin** [comment]
> Do you know when you will release the 1.7 version?

Quoting my earlier comment: "I'm new to this Jenkins plugin maintenance thing and can't figure out how to make releases :/"

I need to find some time to read and understand https://wiki.jenkins-ci.org/display/JENKINS/Hosting+Plugins#HostingPlugins-Releasingtojenkinsci.org, I guess?  Also, I'm not sure I have the permissions to make/upload releases...

**Comment by alecharp** [comment]
@mgedmin few questions then: do you have access to Jira/Wiki? It seems that you are not part of the "JenkinsCI", then do you want to become the official maintainer of this plugin? If so, ask to be added in the JenkinsCI community in GitHub, this will grant you commit access to plugin repository. Then you will need to add your Jira/Wiki credentials to `settings.xml` file as said in the link you quoted. You can test your credential doing a `mvn deploy` on the SNAPSHOT code. Finally, you will be able to do `mvn release:prepare release:perform -B`.

Maybe I should rename my PR to "Re-indent SVG files" and set the plastic images height back to 18px. Do you agree?

**Comment by mgedmin** [comment]
I have access to Jira and the wiki, yes.  I would like to be able to do releases.

**Comment by daniel-beck** [comment]
If you have commit permissions to this repo and an account for Wiki/Jira, you can perform releases.

You're not a member of the jenkinsci org on GitHub though, but appear to be able to commit to this repo (merged pull requests etc.). How did you accomplish that?

**Comment by mgedmin** [comment]
I asked for commit rights on the mailing list. :)

I am a member of the jenkinsci org on GitHub, but my membership status was private for some reason.

**Comment by alecharp** [comment]
I think you can commit on this repo as you already merged pull request by the past.

**Comment by mgedmin** [comment]
`mvn deploy` seems to have succeeded (although I HAVE NO IDEA WHAT IT WAS THAT IT DID, other than running tests and building an .hpi and uploading something somewhere under http://maven.jenkins-ci.org:8081 WHICH DOES IT MEAN IT'S TRANSMITTING MY USERNAME AND PASSWORD OVER PLAINTEXT HTTP OR WHAT SERIOUSLY?

Um.

Anyway, I'm supposed to edit pom.xml and change the version number to 1.7 without -SNAPSHOT, right?  And then commit?  And then run `mvn release:prepare release:perform -B`?  Or will `mvn release` do the pom.xml changes for me?

**Comment by mgedmin** [comment]
So 1.7 should be out now.  I'm currently having trouble updating the changelog on the wiki, but it'll say

> h5. 1.7 (Mar 24, 2015)
> 
> * New badge style: flat, with option to choose the old ("plastic") style ([26705@issue])
> * Option to omit view name from the URL ([26585@issue])

**Comment by alecharp** [comment]
Too bad you didn't merge this PR before releasing. But thank you anyway

**Comment by mgedmin** [comment]
Sorry!  I'm a bit overwhelmed with stuff right now.

What did you use to pretty-print the XML?  I'll want to use the same tool in the future should the shields.io style change again, to minimize the diff.

**Comment by alecharp** [comment]
In this case, no tool. I did the indentation by hand.

**Comment by mgedmin** [comment]
I ran the SVG files on master and the SVG files in your pull request through `xmllint --format` (from libxml2-utils) and compared them.  There are differences:
```diff
$ git fetch origin '+refs/pull/*/head:refs/remotes/origin/pull/*'
$ git checkout pull/14
$ cd src/main/webapp/status/
$ for i in *.svg; do pretty-print-xml $i > /tmp/two-$i; done
$ git checkout master
$ for i in *.svg; do pretty-print-xml $i > /tmp/one-$i; done
$ for i in *.svg; do colordiff -u /tmp/one-$i /tmp/two-$i; done
--- /tmp/one-build-failing-red.svg	2015-03-25 20:58:42.276427241 +0200
+++ /tmp/two-build-failing-red.svg	2015-03-25 20:58:34.952339977 +0200
@@ -8,7 +8,7 @@
   </linearGradient>
   <rect rx="4" width="81" height="18" fill="#555"/>
   <rect rx="4" x="37" width="44" height="18" fill="#e05d44"/>
-  <path fill="#e05d44" d="M37 0h4v18h-4z"/>
+  <path fill="#e05d44" d="M37 0h4v20h-4z"/>
   <rect rx="4" width="81" height="18" fill="url(#a)"/>
   <g fill="#fff" text-anchor="middle" font-family="DejaVu Sans,Verdana,Geneva,sans-serif" font-size="11">
     <text x="19.5" y="13" fill="#010101" fill-opacity=".3">build</text>
--- /tmp/one-build-passing-brightgreen.svg	2015-03-25 20:58:42.284427337 +0200
+++ /tmp/two-build-passing-brightgreen.svg	2015-03-25 20:58:34.960340073 +0200
@@ -8,7 +8,7 @@
   </linearGradient>
   <rect rx="4" width="90" height="18" fill="#555"/>
   <rect rx="4" x="37" width="53" height="18" fill="#4c1"/>
-  <path fill="#4c1" d="M37 0h4v18h-4z"/>
+  <path fill="#4c1" d="M37 0h4v20h-4z"/>
   <rect rx="4" width="90" height="18" fill="url(#a)"/>
   <g fill="#fff" text-anchor="middle" font-family="DejaVu Sans,Verdana,Geneva,sans-serif" font-size="11">
     <text x="19.5" y="13" fill="#010101" fill-opacity=".3">build</text>
--- /tmp/one-build-running-blue.svg	2015-03-25 20:58:42.292427432 +0200
+++ /tmp/two-build-running-blue.svg	2015-03-25 20:58:34.968340168 +0200
@@ -8,7 +8,7 @@
   </linearGradient>
   <rect rx="4" width="90" height="18" fill="#555"/>
   <rect rx="4" x="37" width="53" height="18" fill="#007ec6"/>
-  <path fill="#007ec6" d="M37 0h4v18h-4z"/>
+  <path fill="#007ec6" d="M37 0h4v20h-4z"/>
   <rect rx="4" width="90" height="18" fill="url(#a)"/>
   <g fill="#fff" text-anchor="middle" font-family="DejaVu Sans,Verdana,Geneva,sans-serif" font-size="11">
     <text x="19.5" y="13" fill="#010101" fill-opacity=".3">build</text>
--- /tmp/one-build-unknown-lightgrey.svg	2015-03-25 20:58:42.300427526 +0200
+++ /tmp/two-build-unknown-lightgrey.svg	2015-03-25 20:58:34.976340263 +0200
@@ -8,7 +8,7 @@
   </linearGradient>
   <rect rx="4" width="98" height="18" fill="#555"/>
   <rect rx="4" x="37" width="61" height="18" fill="#9f9f9f"/>
-  <path fill="#9f9f9f" d="M37 0h4v18h-4z"/>
+  <path fill="#9f9f9f" d="M37 0h4v20h-4z"/>
   <rect rx="4" width="98" height="18" fill="url(#a)"/>
   <g fill="#fff" text-anchor="middle" font-family="DejaVu Sans,Verdana,Geneva,sans-serif" font-size="11">
     <text x="19.5" y="13" fill="#010101" fill-opacity=".3">build</text>
--- /tmp/one-build-unstable-yellow.svg	2015-03-25 20:58:42.304427575 +0200
+++ /tmp/two-build-unstable-yellow.svg	2015-03-25 20:58:34.984340359 +0200
@@ -8,7 +8,7 @@
   </linearGradient>
   <rect rx="4" width="95" height="18" fill="#555"/>
   <rect rx="4" x="37" width="58" height="18" fill="#dfb317"/>
-  <path fill="#dfb317" d="M37 0h4v18h-4z"/>
+  <path fill="#dfb317" d="M37 0h4v20h-4z"/>
   <rect rx="4" width="95" height="18" fill="url(#a)"/>
   <g fill="#fff" text-anchor="middle" font-family="DejaVu Sans,Verdana,Geneva,sans-serif" font-size="11">
     <text x="19.5" y="13" fill="#010101" fill-opacity=".3">build</text>

```

**Comment by mgedmin** [comment]
Would you like me to run the pretty-printing script that I have on master?  Or would you prefer to fix your PR and get your name in the commit log?

Incidentally, the difference between your manual formatting and output produced by xmllint looks like this:
```diff
$ git checkout pull/14
$ diff -u /tmp/one-build-passing-brightgreen.svg build-passing-brightgreen.svg
--- /tmp/one-build-passing-brightgreen.svg	2015-03-25 20:58:42.284427337 +0200
+++ build-passing-brightgreen.svg	2015-03-25 21:03:03.967529917 +0200
@@ -1,4 +1,3 @@
-<?xml version="1.0"?>
 <svg xmlns="http://www.w3.org/2000/svg" width="90" height="18">
   <linearGradient id="a" x2="0" y2="100%">
     <stop offset="0" stop-color="#fff" stop-opacity=".7"/>
@@ -8,7 +7,7 @@
   </linearGradient>
   <rect rx="4" width="90" height="18" fill="#555"/>
   <rect rx="4" x="37" width="53" height="18" fill="#4c1"/>
-  <path fill="#4c1" d="M37 0h4v18h-4z"/>
+  <path fill="#4c1" d="M37 0h4v20h-4z"/>
   <rect rx="4" width="90" height="18" fill="url(#a)"/>
   <g fill="#fff" text-anchor="middle" font-family="DejaVu Sans,Verdana,Geneva,sans-serif" font-size="11">
     <text x="19.5" y="13" fill="#010101" fill-opacity=".3">build</text>
@@ -16,4 +15,4 @@
     <text x="62.5" y="13" fill="#010101" fill-opacity=".3">passing</text>
     <text x="62.5" y="12">passing</text>
   </g>
-</svg>
+</svg>
\ No newline at end of file
```

I like files to have trailing newlines (it's technically required for text files on Unix).  I'm less sanguine about the extra `<?xml?>` declaration; it seems entirely unnecessary.  If I'll run the script, I'll strip those out.

**Comment by alecharp** [comment]
I think your first `diff` was before I rollbacked the images to 18px high. 
My last commit include `xmllint` validation of the SVG plastic and flat images.

**Comment by mgedmin** [comment]
> I think your first diff was before I rollbacked the images to 18px high. 

Nope.

I think your rollback was incomplete.

Look, here's [build-passing-brightgreen.svg](https://github.com/jenkinsci/embeddable-build-status-plugin/blob/master/src/main/webapp/status/build-passing-brightgreen.svg?short_path=07f815b) on master:
> ekrano nuotrauka is 2015-03-26 19 07 59

`<path fill="#4c1" d="M37 0h4v18h-4z"/>`

And here's your [build-passing-brightgreen.svg](https://github.com/alecharp/embeddable-build-status-plugin/blob/master/src/main/webapp/status/build-passing-brightgreen.svg?short_path=31b33cc#L11):
> ekrano nuotrauka is 2015-03-26 19 10 27

`<path fill="#4c1" d="M37 0h4v20h-4z"/>`

**Comment by mgedmin** [comment]
I didn't notice your latest commit at first because GitHub doesn't send notification emails about new commits being added to pull requests.  Sorry!

There's one remaining little issue: https://github.com/alecharp/embeddable-build-status-plugin/blob/master/src/main/webapp/status/build-passing-brightgreen.svg?short_path=31b33cc#L11 is broken and cannot be displayed, because

```diff
--- /tmp/one-build-passing-brightgreen.svg	2015-03-30 09:27:54.056899542 +0300
+++ /tmp/two-build-passing-brightgreen.svg	2015-03-30 09:28:02.452957305 +0300
@@ -1,5 +1,5 @@
 <?xml version="1.0"?>
-<svg xmlns="http://www.w3.org/1800/svg" width="90" height="18">
+<svg xmlns="http://www.w3.org/2000/svg" width="90" height="18">
   <linearGradient id="a" x2="0" y2="100%">
     <stop offset="0" stop-color="#fff" stop-opacity=".7"/>
     <stop offset=".1" stop-color="#aaa" stop-opacity=".1"/>
```

I think the search-and-replace of 20 -> 18 got awry and mangled the XML namespace.

**Comment by mgedmin** [comment]
I didn't notice your latest commit at first because GitHub doesn't send notification emails about new commits being added to pull requests.  Sorry!

There's one remaining little issue: https://github.com/alecharp/embeddable-build-status-plugin/blob/master/src/main/webapp/status/build-passing-brightgreen.svg?short_path=31b33cc#L11 is broken and cannot be displayed, because

```diff
--- /tmp/one-build-passing-brightgreen.svg	2015-03-30 09:27:54.056899542 +0300
+++ /tmp/two-build-passing-brightgreen.svg	2015-03-30 09:28:02.452957305 +0300
@@ -1,5 +1,5 @@
 <?xml version="1.0"?>
-<svg xmlns="http://www.w3.org/1800/svg" width="90" height="18">
+<svg xmlns="http://www.w3.org/2000/svg" width="90" height="18">
   <linearGradient id="a" x2="0" y2="100%">
     <stop offset="0" stop-color="#fff" stop-opacity=".7"/>
     <stop offset=".1" stop-color="#aaa" stop-opacity=".1"/>
```

I think the search-and-replace of 20 -> 18 got awry and mangled the XML namespace.

**Comment by alecharp** [comment]
I'm sorry for that. It seems that I introduce that in d637d1c, during my find/replace.

**Comment by mgedmin** [comment]
Thank you!

**Pull request merged**
